export enum Civic {
    AgrarianIdyll = 'Agrarian Idyll',
    Anglers = 'Anglers',
    AristocraticElite = 'Aristocratic Elite',
    BarbaricDespoilers = 'Barbaric Despoilers',
    BeaconOfLiberty = 'Beacon of Liberty',
    ByzantineBureaucracy = 'Byzantine Bureaucracy',
    CatalyticProcessing = 'Catalytic Processing',
    CitizenService = 'Citizen Service',
    CorporateDominion = 'Corporate Dominion',
    CorveeSystem = 'Corvee System',
    CutthroatPolitics = 'Cutthroat Politics',
    DeathCult = 'Death Cult',
    DiplomaticCorps = 'Diplomatic Corps',
    DistinguishedAdmiralty = 'Distinguished Admiralty',
    EfficientBureaucracy = 'Efficient Bureaucracy',
    Environmentalist = 'Environmentalist',
    ExaltedPriesthood = 'Exalted Priesthood',
    FanaticPurifiers = 'Fanatic Purifiers',
    FeudalRealm = 'Feudal Realm',
    FreeHaven = 'Free Haven',
    FunctionalArchitecture = 'Functional Architecture',
    IdealisticFoundation = 'Idealistic Foundation',
    IdyllicBloom = 'Idyllic Bloom',
    ImperialCult = 'Imperial Cult',
    InwardsPerfection = 'Inwards Perfection',
    MasterfulCrafters = 'Masterful Crafters',
    Memorialist = 'Memorialist',
    MerchantGuilds = 'Merchant Guilds',
    Meritocracy = 'Meritocracy',
    MiningGuilds = 'Mining Guilds',
    NationalisticZeal = 'Nationalistic Zeal',
    ParliamentarySystem = 'Parliamentary System',
    PhilosopherKing = 'Philosopher King',
    PleasureSeekers = 'Pleasure Seekers',
    PoliceState = 'Police State',
    PompousPurists = 'Pompous Purists',
    ReanimatedArmies = 'Reanimated Armies',
    ShadowCouncil = 'Shadow Council',
    SharedBurden = 'Shared Burden',
    SlaverGuilds = 'Slaver Guilds',
    Technocracy = 'Technocracy',
    WarriorCulture = 'Warrior Culture',
    HiveAscetic = 'Ascetic',
    HiveCatalyticProcessing = 'Catalytic Processing',
    HiveDevouringSwarm = 'Devouring Swarm',
    HiveDividedAttention = 'Divided Attention',
    HiveEmpath = 'Empath',
    HiveIdyllicBloom = 'IdyllicBloom',
    HiveMemorialist = 'Memorialist',
    HiveNaturalNeuralNetwork = 'Natural Neural Network',
    HiveOneMind = 'One Mind',
    HivePooledKnowledge = 'Pooled Knowledge',
    HiveStrengthOfLegions = 'Strength of Legions',
    HiveSubspaceEphapse = 'Subspace Ephapse',
    HiveSubsumedWill = 'Subsumed Will',
    HiveTerravore = 'Terravore',
    MachineCatalyticProcessing = 'Catalytic Processing',
    MachineBuilder = 'Builder',
    MachineDelegatedFunctions = 'Delegated Functions',
    MachineTerminator = 'Determined Exterminator',
    MachineAssimilator = 'Driven Assimilator',
    MachineFactoryOverclock = 'Factory Overclock',
    MachineMaintenanceProtocols = 'Maintenance Protocols',
    MachineMemorialist = 'Memorialist',
    MachineIntrospective = 'Introspective',
    MachineOtaUpdates = 'OTA Updates',
    MachinePredictiveAnalysis = 'Predictive Analysis',
    MachineReplication = 'Machine Replication',
    MachineRockbreakers = 'Rock Breaker',
    MachineServitor = 'Rogue Servitor',
    MachineUnitaryCohesion = 'Unitary Cohesion',
    MachineWarbots = 'Warbots',
    MachineZeroWasteProtocols = 'Zero Waste Protocols',
    CorporateAnglers = 'Anglers',
    CorporateBrandLoyalty = 'Brand Loyalty',
    CorporateCatalyticProcessing = 'Catalytic Processing',
    CorporateDeathCult = 'Corporate Death Cult',
    CorporateHedonism = 'Corporate Hedonism',
    CorporateCriminalHeritage = 'Criminal Heritage',
    CorporateFranchising = 'Franchising',
    CorporateFreeTraders = 'Free Traders',
    CorporateGospelOfTheMasses = 'Gospel of The Masses',
    CorporateIndenturedAssets = 'Indentured Assets',
    CorporateCrafters = 'Crafters Inc.',
    CorporateMediaConglomerate = 'Media Conglomerate',
    CorporateNavalContractors = 'Naval Contractors',
    CorporatePrivateMilitaryCompanies = 'Private Military Companies',
    CorporatePrivateProspectors = 'Private Prospectors',
    CorporatePublicRelationsSpecialists = 'Public Relations Specialists',
    CorporateRuthlessCompetition = 'Ruthless Competition',
    CorporateTradingPosts = 'Trading Posts',

}

export const civicIdToCivic = new Map<string, Civic>([
    ['civic_agrarian_idyll', Civic.AgrarianIdyll],
    ['civic_anglers', Civic.Anglers],
    ['civic_aristocratic_elite', Civic.AristocraticElite],
    ['civic_barbaric_despoilers', Civic.BarbaricDespoilers],
    ['civic_beacon_of_liberty', Civic.BeaconOfLiberty],
    ['civic_byzantine_bureaucracy', Civic.ByzantineBureaucracy],
    ['civic_catalytic_processing', Civic.CatalyticProcessing],
    ['civic_citizen_service', Civic.CitizenService],
    ['civic_corporate_dominion', Civic.CorporateDominion],
    ['civic_corvee_system', Civic.CorveeSystem],
    ['civic_cutthroat_politics', Civic.CutthroatPolitics],
    ['civic_death_cult', Civic.DeathCult],
    ['civic_diplomatic_corps', Civic.DiplomaticCorps],
    ['civic_distinguished_admiralty', Civic.DistinguishedAdmiralty],
    ['civic_efficient_bureaucracy', Civic.EfficientBureaucracy],
    ['civic_environmentalist', Civic.Environmentalist],
    ['civic_exalted_priesthood', Civic.ExaltedPriesthood],
    ['civic_fanatic_purifiers', Civic.FanaticPurifiers],
    ['civic_feudal_realm', Civic.FeudalRealm],
    ['civic_free_haven', Civic.FreeHaven],
    ['civic_functional_architecture', Civic.FunctionalArchitecture],
    ['civic_idealistic_foundation', Civic.IdealisticFoundation],
    ['civic_idyllic_bloom', Civic.IdyllicBloom],
    ['civic_imperial_cult', Civic.ImperialCult],
    ['civic_inwards_perfection', Civic.InwardsPerfection],
    ['civic_crafters', Civic.MasterfulCrafters],
    ['civic_memorialist', Civic.Memorialist],
    ['civic_merchant_guilds', Civic.MerchantGuilds],
    ['civic_meritocracy', Civic.Meritocracy],
    ['civic_mining_guilds', Civic.MiningGuilds],
    ['civic_nationalistic_zeal', Civic.NationalisticZeal],
    ['civic_parliamentary_system', Civic.ParliamentarySystem],
    ['civic_philosopher_king', Civic.PhilosopherKing],
    ['civic_pleasure_seekers', Civic.PleasureSeekers],
    ['civic_police_state', Civic.PoliceState],
    ['civic_pompous_purists', Civic.PompousPurists],
    ['civic_reanimated_armies', Civic.ReanimatedArmies],
    ['civic_shadow_council', Civic.ShadowCouncil],
    ['civic_shared_burden', Civic.SharedBurden],
    ['civic_slaver_guilds', Civic.SlaverGuilds],
    ['civic_technocracy', Civic.Technocracy],
    ['civic_warrior_culture', Civic.WarriorCulture],
    ['civic_hive_ascetic', Civic.HiveAscetic],
    ['civic_hive_catalytic_processing', Civic.HiveCatalyticProcessing],
    ['civic_hive_devouring_swarm', Civic.HiveDevouringSwarm],
    ['civic_hive_terravore', Civic.HiveTerravore],
    ['civic_hive_divided_attention', Civic.HiveDividedAttention],
    ['civic_hive_empath', Civic.HiveEmpath],
    ['civic_hive_idyllic_bloom', Civic.HiveIdyllicBloom],
    ['civic_hive_memorialist', Civic.HiveMemorialist],
    ['civic_hive_natural_neural_network', Civic.HiveNaturalNeuralNetwork],
    ['civic_hive_one_mind', Civic.HiveOneMind],
    ['civic_hive_pooled_knowledge', Civic.HivePooledKnowledge],
    ['civic_hive_strength_of_legions', Civic.HiveStrengthOfLegions],
    ['civic_hive_subspace_ephapse', Civic.HiveSubspaceEphapse],
    ['civic_hive_subsumed_will', Civic.HiveSubsumedWill],
    ['civic_machine_catalytic_processing', Civic.MachineCatalyticProcessing],
    ['civic_machine_builder', Civic.MachineBuilder],
    ['civic_machine_delegated_functions', Civic.MachineDelegatedFunctions],
    ['civic_machine_terminator', Civic.MachineTerminator],
    ['civic_machine_assimilator', Civic.MachineAssimilator],
    ['civic_machine_factory_overclock', Civic.MachineFactoryOverclock],
    ['civic_machine_maintenance_protocols', Civic.MachineMaintenanceProtocols],
    ['civic_machine_memorialist', Civic.MachineMemorialist],
    ['civic_machine_introspective', Civic.MachineIntrospective],
    ['civic_machine_ota_updates', Civic.MachineOtaUpdates],
    ['civic_machine_predictive_analysis', Civic.MachinePredictiveAnalysis],
    ['civic_machine_replication', Civic.MachineReplication],
    ['civic_machine_rockbreakers', Civic.MachineRockbreakers],
    ['civic_machine_servitor', Civic.MachineServitor],
    ['civic_machine_unitary_cohesion', Civic.MachineUnitaryCohesion],
    ['civic_machine_warbots', Civic.MachineWarbots],
    ['civic_machine_zero_waste_protocols', Civic.MachineZeroWasteProtocols],
    ['civic_corporate_anglers', Civic.CorporateAnglers],
    ['civic_brand_loyalty', Civic.CorporateBrandLoyalty],
    ['civic_corporate_catalytic_processing', Civic.CorporateCatalyticProcessing],
    ['civic_death_cult_corporate', Civic.CorporateDeathCult],
    ['civic_corporate_hedonism', Civic.CorporateHedonism],
    ['civic_criminal_heritage', Civic.CorporateCriminalHeritage],
    ['civic_franchising', Civic.CorporateFranchising],
    ['civic_free_traders', Civic.CorporateFreeTraders],
    ['civic_gospel_of_the_masses', Civic.CorporateGospelOfTheMasses],
    ['civic_indentured_assets', Civic.CorporateIndenturedAssets],
    ['civic_corporate_crafters', Civic.CorporateCrafters],
    ['civic_media_conglomerate', Civic.CorporateMediaConglomerate],
    ['civic_naval_contractors', Civic.CorporateNavalContractors],
    ['civic_private_military_companies', Civic.CorporatePrivateMilitaryCompanies],
    ['civic_private_prospectors', Civic.CorporatePrivateProspectors],
    ['civic_public_relations_specialists', Civic.CorporatePublicRelationsSpecialists],
    ['civic_ruthless_competition', Civic.CorporateRuthlessCompetition],
    ['civic_trading_posts', Civic.CorporateTradingPosts],
])