export enum Origin {
    ProsperousUnification = 'Prosperous Unification',
    GalacticDoorstep = 'Galactic Doorstep',
    LostColony = 'Lost Colony',
    Mechanist = 'Mechanist',
    SyncreticEvolution = 'Syncretic Evolution',
    TreeOfLife = 'Tree Of Life',
    ResourceConsolidation = 'Resource Consolidation',
    CloneArmy = 'Clone Army',
    LifeSeeded = 'Life Seeded',
    PostApocalyptic = 'Post Apocalyptic',
    Remnants = 'Remnants',
    CalamitousBirth = 'Calamitous Birth',
    CommonGround = 'Common Ground',
    Hegemon = 'Hegemon',
    Doomsday = 'Doomsday',
    OnTheShouldersOfGiants = 'On The Shoulders Of Giants',
    Scion = 'Scion',
    ShatteredRing = 'Shattered Ring',
    VoidDwellers = 'Void Dwellers',
    Necrophage = 'Necrophage',
    HereBeDragons = 'Here Be Dragons',
    OceanParadise = 'Ocean Paradise'
}

export const originFromOriginString = new Map<string, Origin>([
    ['origin_default', Origin.ProsperousUnification],
    ['origin_mechanists', Origin.Mechanist],
    ['origin_syncretic_evolution', Origin.SyncreticEvolution],
    ['origin_life_seeded', Origin.LifeSeeded],
    ['origin_post_apocalyptic', Origin.PostApocalyptic],
    ['origin_remnants', Origin.Remnants],
    ['origin_shattered_ring', Origin.ShatteredRing],
    ['origin_void_dwellers', Origin.VoidDwellers],
    ['origin_scion', Origin.Scion],
    ['origin_galactic_doorstep', Origin.GalacticDoorstep],
    ['origin_tree_of_life', Origin.TreeOfLife],
    ['origin_shoulders_of_giants', Origin.OnTheShouldersOfGiants],
    ['origin_lithoid', Origin.CalamitousBirth],
    ['origin_machine', Origin.ResourceConsolidation],
    ['origin_common_ground', Origin.CommonGround],
    ['origin_hegemon', Origin.Hegemon],
    ['origin_doomsday', Origin.Doomsday],
    ['origin_lost_colony', Origin.LostColony],
    ['origin_necrophage', Origin.Necrophage],
    ['origin_clone_army', Origin.CloneArmy],
    ['origin_here_be_dragons', Origin.HereBeDragons],
    ['origin_ocean_paradise', Origin.OceanParadise]
])

