export enum Trait {
    Adaptive = 'Adaptive',
    Agrarian =  'Agrarian',
    Charismatic = 'Charismatic',
    Communal = 'Communal',
    Conformists = 'Conformists',
    Conservationist = 'Conservationist',
    Docile = 'Docile',
    Enduring = 'Enduring',
    Industrious = 'Industrious',
    Ingenious = 'Ingenious',
    Intelligent = 'Intelligent',
    NaturalEngineers = 'Natural Engineers',
    NaturalPhysicists = 'Natural Physicists',
    NaturalSociologists = 'Natural Sociologists',
    Nomadic = 'Nomadic',
    QuickLearners = 'Quick Learners',
    RapidBreeders = 'Rapid Breeders',
    Resilient = 'Resilient',
    Strong = 'Strong',
    Talented = 'Talented',
    Thrifty = 'Thrifty',
    Traditional = 'Traditional',
    HiveMinded = 'Hive Minded',
    Mechanical = 'Mechanical',
    Necrophage = 'Necrophage' ,
    Aquatic = 'Aquatic',
    Budding = 'Budding',
    Phototrophic = 'Phototrophic',
    Radiotrophic = 'Radiotrophic',
    Lithoid = 'Lithoid',
    GaseousByproducts = 'Gaseous Byproducts',
    ScintillatingSkin = 'Scintillating Skin',
    VolatileExcretions = 'Volatile Excretions',
    CloneSoldier = 'Clone Soldier',
    Serviles = 'Serviles',
    Survivor = 'Survivor',
    VoidDweller = 'Void Dweller',
    Decadent = 'Decadent',
    Deviants = 'Deviants',
    Fleeting = 'Fleeting',
    Nonadaptive = 'Non adaptive',
    Quarrelsome = 'Quarrelsome',
    Repugnant = 'Repugnant',
    SlowBreeders = 'Slow Breeders',
    SlowLearners = 'Slow Learners',
    Sedentary = 'Sedentary',
    Solitary = 'Solitary',
    Unruly = 'Unruly',
    Wasteful = 'Wasteful',
    Weak = 'Weak',
    Bulky = 'Bulky',
    CustomMade = 'Custom Made',
    HighBandwidth = 'High Bandwidth',
    HighMaintenance = 'High Maintenance',
    Luxurious = 'Luxurious',
    RepurposedHardware = 'Repurposed Hardware',
    Uncanny = 'Uncanny',
    VeryStrong = 'Very Strong',
    Machine = 'Machine',
    DomesticProtocols = 'Domestic Protocols',
    DoubleJointed = 'Double Jointed',
    Durable = 'Durable',
    EfficientProcessors = 'Efficient Processors',
    EmotionEmulators = 'Emotion Emulators',
    EnhancedMemory = 'Enhanced Memory',
    Harvesters = 'Harvesters',
    LearningAlgorithms = 'Learning Algorithms',
    LogicEngines = 'Logic Engines',
    LoyaltyCircuits = 'Loyalty Circuits',
    MassProduced = 'Mass Produced',
    PowerDrills = 'Power Drills',
    PropagandaMachines = 'Propaganda Machines',
    Recycled = 'Recycled',
    StreamlinedProtocols = 'Streamlined Protocols',
    Superconductive = 'Superconductive',
    ExtremelyAdaptive = 'Extremely Adaptive',
}

export const traitFromTraitString = new Map<string, Trait>([
    ['trait_adaptive', Trait.Adaptive],
    ['trait_agrarian', Trait.Agrarian],
    ['trait_charismatic', Trait.Charismatic],
    ['trait_communal', Trait.Communal],
    ['trait_conformists', Trait.Conformists],
    ['trait_conservational', Trait.Conservationist],
    ['trait_docile', Trait.Docile],
    ['trait_enduring', Trait.Enduring],
    ['trait_industrious', Trait.Industrious],
    ['trait_ingenious', Trait.Ingenious],
    ['trait_intelligent', Trait.Intelligent],
    ['trait_natural_engineers', Trait.NaturalEngineers],
    ['trait_natural_physicists', Trait.NaturalPhysicists],
    ['trait_natural_sociologists', Trait.NaturalSociologists],
    ['trait_nomadic', Trait.Nomadic],
    ['trait_quick_learners', Trait.QuickLearners],
    ['trait_rapid_breeders', Trait.RapidBreeders],
    ['trait_resilient', Trait.Resilient],
    ['trait_strong', Trait.Strong],
    ['trait_talented', Trait.Talented],
    ['trait_thrifty', Trait.Thrifty],
    ['trait_traditional', Trait.Traditional],
    ['trait_hive_mind', Trait.HiveMinded],
    ['trait_mechanical', Trait.Mechanical],
    ['trait_necrophage', Trait.Necrophage],
    ['trait_aquatic', Trait.Aquatic],
    ['trait_plantoid_budding', Trait.Budding],
    ['trait_plantoid_phototrophic', Trait.Phototrophic],
    ['trait_plantoid_radiotrophic', Trait.Radiotrophic],
    ['trait_lithoid', Trait.Lithoid],
    ['trait_lithoid_gaseous_byproducts', Trait.GaseousByproducts],
    ['trait_lithoid_scintillating', Trait.ScintillatingSkin],
    ['trait_lithoid_volatile_excretions', Trait.VolatileExcretions],
    ['trait_clone_soldier_infertile', Trait.CloneSoldier],
    ['trait_syncretic_proles', Trait.Serviles],
    ['trait_survivor', Trait.Survivor],
    ['trait_void_dweller_1', Trait.VoidDweller],
    ['trait_decadent', Trait.Decadent],
    ['trait_deviants', Trait.Deviants],
    ['trait_fleeting', Trait.Fleeting],
    ['trait_nonadaptive', Trait.Nonadaptive],
    ['trait_quarrelsome', Trait.Quarrelsome],
    ['trait_repugnant', Trait.Repugnant],
    ['trait_slow_breeders', Trait.SlowBreeders],
    ['trait_slow_learners', Trait.SlowLearners],
    ['trait_sedentary', Trait.Sedentary],
    ['trait_solitary', Trait.Solitary],
    ['trait_unruly', Trait.Unruly],
    ['trait_wasteful', Trait.Wasteful],
    ['trait_weak', Trait.Weak],
    ['trait_robot_bulky', Trait.Bulky],
    ['trait_robot_custom_made', Trait.CustomMade],
    ['trait_robot_high_bandwidth', Trait.HighBandwidth],
    ['trait_robot_high_maintenance', Trait.HighMaintenance],
    ['trait_robot_luxurious', Trait.Luxurious],
    ['trait_robot_repurposed_hardware', Trait.RepurposedHardware],
    ['trait_robot_uncannyVenerable', Trait.Uncanny],
    ['trait_very_strong', Trait.VeryStrong],
    ['trait_machine_unit', Trait.Machine],
    ['trait_robot_domestic_protocols', Trait.DomesticProtocols],
    ['trait_robot_double_jointed', Trait.DoubleJointed],
    ['trait_robot_durable', Trait.Durable],
    ['trait_robot_efficient_processors', Trait.EfficientProcessors],
    ['trait_robot_emotion_emulators', Trait.EmotionEmulators],
    ['trait_robot_enhanced_memory', Trait.EnhancedMemory],
    ['trait_robot_harvesters', Trait.Harvesters],
    ['trait_robot_learning_algorithms', Trait.LearningAlgorithms],
    ['trait_robot_logic_engines', Trait.LogicEngines],
    ['trait_robot_loyalty_circuits', Trait.LoyaltyCircuits],
    ['trait_robot_mass_produced', Trait.MassProduced],
    ['trait_robot_power_drills', Trait.PowerDrills],
    ['trait_robot_propaganda_machines', Trait.PropagandaMachines],
    ['trait_robot_recycled', Trait.Recycled],
    ['trait_robot_streamlined_protocols', Trait.StreamlinedProtocols],
    ['trait_robot_superconductive', Trait.Superconductive],
    ['trait_extremely_adaptive', Trait.ExtremelyAdaptive],
])